framework:
    workflows:
           Mission:
               type: 'state_machine' # or 'state_machine'
               audit_trail:
                   enabled: true
               marking_store:
                   type: 'method'
                   property: 'etat'            
               supports: 
                   - App\Entity\Mission
               initial_marking: en_cours
               places:
                   - en_cours
                   - termine
               transitions:
                   valider:
                       from: en_cours
                       to: termine

           Demande:
                type: 'state_machine' # or 'state_machine'
                audit_trail:
                    enabled: true
                marking_store:
                    type: 'method'
                    property: 'etat'            
                supports:
                    - App\Entity\Demande
                initial_marking: en_cours
                places:
                    - en_cours
                    - valider
                    - livree
                transitions:
                    valider:
                        from: en_cours
                        to: valider
                    livraison:
                        from: valider
                        to: livree

#         dossier:
#             type: 'workflow' # or 'state_machine'
#             audit_trail:
#                 enabled: true
#             marking_store:
#                 type: 'method'
#                 property: 'etat'            
#             supports: 
#                 - App\Entity\Mission
#             initial_marking: en_cours
#             places:
                
#                 - en_cours
#                 - termine
#             transitions:
#                 post_creation:
#                     from: cree
#                     to: en_cours
#                 cloture:
#                     from: en_cours
#                     to: termine

#         constitution:
#             type: 'workflow' # or 'state_machine'
#             audit_trail:
#                 enabled: true
#             marking_store:
#                 type: 'method'
#                 property: 'etat'            
#             supports: 
#                 - App\Entity\ActeConstitution
#             initial_marking: cree
#             places:
#                 - cree
#                 - termine
#             transitions:
#                 cloture:
#                     from: cree
#                     to: termine